name: intellagent
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - google-cloud-aiplatform==1.75.0
      - anthropic[vertex]==0.42.0
      - langchain_google_vertexai==2.0.9
      - langchain==0.3.7
      - langchain_core==0.3.15
      - langchain_openai==0.2.5
      - langgraph==0.2.44
      - pandas==2.2.3
      - langchain_community==0.3.5
      - networkx==3.2.1
      - streamlit==1.39.0
      - plotly==5.24.1
      - langchain_google_genai==2.0.7
